Odświeżanie ekranów na Androidzie.
Samograje/co-gdzie-kiedy pull request #175
Opened 2020-01-20 22:27 UTC by kamil-rusin

2020-01-21 16:12 UTC, bartlomiej-szlachta requested changes
Jeszcze błędy są w dwóch miejscach:
- nie odświeża się strona główna
- skaner kodów QR skanuje nawet będąc na innym ekranie

2020-01-21 16:12 UTC, bartlomiej-szlachta commented on frontend/src/components/affiliations/AffiliationsListContainer.jsx
> +      const {navigation} = this.props;
Nie wykorzystujesz `navigation`, więc nie trzeba go tutaj deklarować. Tak samo na pozostałych ekranach

2020-01-22 18:15 UTC, kamil-rusin commented on frontend/src/components/affiliations/AffiliationsListContainer.jsx
> +      const {navigation} = this.props;
Done

2020-01-22 18:29 UTC, bartlomiej-szlachta approved these changes
Gites 😎

2020-01-22 18:29 UTC, merged